### ISSUE TITLE
Missing Enumeration<T,T> class

### ISSUE THREAD

**Issue by svengl** [zdomokos/IBNet#2]
Hi

Would it be possible to add the Enumeration class, which is referenced in:
Ztg.Common.DataStructures.Enums;
At the moment the project can't be compiled.

Regards

**Comment by zdomokos** [comment]
The missing code is in this nuget https://www.nuget.org/packages/Enumeration/ .  Just add the nuget and it should compile.  I use the source code directly, without the nuget.

**Comment by svengl** [comment]
Ok that works. Thanks
